version: '3'

services:
  blacklist-server:
    build: ./works/command-server/
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - GIN_MODE=release
    volumes:
      - ./logs:/app/logs

  blacklist-client:
    build: ./works/command-client/
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    environment:
      - GIN_MODE=release
    volumes:
      - ./logs:/app/logs

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blacklist
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 