version: '3.8'

services:
  command-server:
    build:
      context: .
      dockerfile: works/command-server/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      - GIN_MODE=release
    volumes:
      - ./configs:/app/configs
      - ./logs:/app/logs
  command-client:
    build:
      context: .
      dockerfile: works/command-client/Dockerfile
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      - GIN_MODE=release
    volumes:
      - ./configs:/app/configs
      - ./logs:/app/logs

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blacklist
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

networks:
  app-network:
    driver: bridge 

volumes:
  postgres_data:
  redis_data: 