version: '3'

services:
  appServer:
    build: ./cmd/server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - CONFIG_PATH=/app/configs/dev
    volumes:
      - ./logs:/app/logs

  appClient:
    build: ./cmd/client
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    environment:
      - CONFIG_PATH=/app/configs/dev
    volumes:
      - ./logs:/app/logs

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blackapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: 