server:
  port: 8080
  mode: debug

database:
  driver: postgres
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: password
  dbname: blacklist
  sslmode: disable

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0

jwt:
  secret: your-secret-key
  expire: 24h

log:
  level: debug
  filename: ./logs/app.log
  maxsize: 100
  maxage: 30
  maxbackups: 10 